### ISSUE TITLE
No Window Show After PyOMIX Runs

### ISSUE THREAD

**Issue by owenzhao** [kspviswa/PyOMlx#3]
I just installed the 0.0.3 release version. No Window was shown. Also the about menu shows it as 0.0.2.

Any idea? 

<img width="328" alt="截屏2024-04-09 16 59 31" src="https://github.com/kspviswa/PyOMlx/assets/2182896/172280c3-4b13-4b92-83aa-520ba1a3195b">

**Comment by kspviswa** [comment]
Pyomlx will be running in background and you can find app icon on the systemtray

**Comment by owenzhao** [comment]
So if I want to mlx, I have to install it manually first?

**Comment by kspviswa** [comment]
Yes... PyOMlx is a mlx sever app. Once you install and run it, it will run the api server in the background . Then when you chat using PyOllaMx, it can then interact with PyOMlx for MLX based models
